name: Escape Room Availability Check

on:
  workflow_dispatch:       # allow manual runs from GitHub UI
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes

jobs:
  check-availability:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Run availability check
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          ONLY_CHAT_ID: ${{ secrets.ONLY_CHAT_ID }}
        run: node escape_availability.js
